# -*- coding: utf-8 -*-
"""CrisisNet_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPSW0BRb-OxpNxVewz3yr2tQzFD9iYOH

# 🚨 CrisisNet — Multimodal Crisis Intelligence

> **Complete Google Colab implementation** with automatic checkpoint saving to Google Drive.

### What this notebook trains
| Stage | Method | Concepts |
|-------|--------|----------|
| 1 | CLIP-style self-supervised pre-training | SSL, CNN, Transformer |
| 2 | Multi-task fine-tuning on CrisisMMD v2.0 | Multimodal, Cross-Attention |
| 3 | Cross-disaster domain adaptation (DANN) | Domain Adaptation |

### Checkpoint behaviour
- After **every epoch**: saves `model_latest.pth` → Google Drive (overwrites)
- After **best epoch**: saves `model_best.pth` → Google Drive  
- On session restart: automatically resumes from `model_latest.pth`

### Dataset
Download **CrisisMMD v2.0** from https://crisisnlp.qcri.org/crisismmd  
*(Free academic access — fill the form and download the zip)*

> If you haven't downloaded yet, set `DEMO_MODE = True` in Cell 3 to run on synthetic data.

## ⚙️ Cell 1 — Install packages
Run once per Colab session.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q transformers==4.40.0 scikit-learn==1.4.0 pandas Pillow matplotlib seaborn tqdm accelerate
# 
# # Verify
# import importlib
# pkgs = ['transformers','sklearn','pandas','PIL','matplotlib','seaborn','tqdm']
# for p in pkgs:
#     assert importlib.util.find_spec(p), f"Missing: {p}"
# print("✅ All packages ready.")

import subprocess, sys

print("Installing packages...")

# ── numpy MUST be force-reinstalled first to fix the ABI mismatch ─
# (ValueError: numpy.dtype size changed = old numpy still in memory)
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q",
     "--force-reinstall", "numpy>=1.26.4,<2.0"],
    check=True
)

# ── everything else ───────────────────────────────────────────────
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q",
     "pandas>=2.0.0",
     "transformers==4.40.0",
     "scikit-learn==1.4.0",
     "Pillow", "matplotlib", "seaborn", "tqdm", "accelerate"],
    check=True
)

print("✅ Packages installed.")
print()
print("━" * 52)
print("  ⚠️  RUNTIME RESTART REQUIRED")
print("  Restarting now — re-run from Cell 2 afterwards.")
print("━" * 52)

# Auto-restart so the fresh numpy binary is actually loaded
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

"""## 📦 Cell 2 — Imports & Reproducibility"""

import os, sys, json, time, math, random, warnings, copy
from pathlib import Path
from typing import Optional, Dict, List, Tuple
from dataclasses import dataclass, asdict
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from PIL import Image
from tqdm.auto import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim import AdamW

# ── Mixed-precision: works on PyTorch 1.x, 2.0, and 2.4+ ────────
# torch.cuda.amp was deprecated in 2.0 and removed in 2.4.
# We import from torch.amp when available, with a thin wrapper so that
# autocast(enabled=...) keeps working exactly as before everywhere.
try:
    from torch.amp import GradScaler as _GradScaler
    def GradScaler(enabled=True):           # noqa: N802
        return _GradScaler(device="cuda", enabled=enabled)

    def autocast(enabled=True):
        _dev = "cuda" if torch.cuda.is_available() else "cpu"
        return torch.amp.autocast(device_type=_dev, enabled=enabled and torch.cuda.is_available())

    print("  AMP  : torch.amp (PyTorch >= 2.0)")

except ImportError:                         # PyTorch < 2.0
    from torch.cuda.amp import autocast, GradScaler
    print("  AMP  : torch.cuda.amp (PyTorch < 2.0)")

import torchvision.models as models
import torchvision.transforms as transforms

from transformers import BertTokenizer, BertModel, get_linear_schedule_with_warmup
from sklearn.metrics import (
    f1_score, classification_report,
    accuracy_score, confusion_matrix,
)

# ── Reproducibility ──────────────────────────────────────────────
SEED = 42
def set_seed(s: int = 42):
    random.seed(s)
    np.random.seed(s)
    torch.manual_seed(s)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(s)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(SEED)

# ── Device ───────────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"  Device: {device}")

if torch.cuda.is_available():
    props = torch.cuda.get_device_properties(0)
    vram  = props.total_memory / 1_073_741_824
    print(f"  GPU   : {props.name}")
    print(f"  VRAM  : {vram:.1f} GiB")
    print(f"  PyTorch: {torch.__version__}")
else:
    print("  No GPU detected — go to Runtime → Change runtime type → T4 GPU")

print("\n✅ Imports complete.")

"""## ⚙️ Cell 3 — Configuration
**Edit `DEMO_MODE` and `DATA_DIR` here.**
"""

# ╔══════════════════════════════════════════════════════════════╗
# ║  Edit DRIVE_BASE if you want a different folder name           ║
# ╚══════════════════════════════════════════════════════════════╝
DRIVE_BASE = '/content/drive/MyDrive/CrisisNet'

@dataclass
class Config:
    # Paths
    drive_base:  str   = DRIVE_BASE
    use_drive:   bool  = True

    # BERT
    bert_name:   str   = 'bert-base-uncased'
    max_len:     int   = 128

    # Architecture
    proj_dim:    int   = 512
    num_heads:   int   = 8
    num_layers:  int   = 2
    dropout:     float = 0.1
    img_size:    int   = 224

    # Class counts — set automatically from HF metadata in Cell 9
    # (HF v2.0 has 3 damage classes, not 4 — dont_know was removed)
    n_inform:    int   = 2
    n_damage:    int   = 3    # ← was 4, now 3
    n_human:     int   = 8
    n_disasters: int   = 7

    # Stage 1 — SSL
    ssl_epochs:  int   = 10
    ssl_bs:      int   = 64
    ssl_lr:      float = 2e-4
    ssl_temp:    float = 0.07
    ssl_wd:      float = 1e-4

    # Stage 2 — Fine-tuning
    ft_epochs:   int   = 20
    ft_bs:       int   = 32
    ft_lr:       float = 2e-5
    ft_warmup:   float = 0.1
    ft_wd:       float = 0.01
    lam_info:    float = 1.0
    lam_dmg:     float = 0.5
    lam_hum:     float = 0.5

    # Stage 3 — DANN
    dann_epochs: int   = 15
    dann_bs:     int   = 32
    dann_lr:     float = 5e-6
    lam_domain:  float = 0.1

    # Misc
    grad_clip:   float = 1.0
    use_amp:     bool  = True

    def ckpt(self, stage):
        base = self.drive_base if self.use_drive else '/content'
        return os.path.join(base, 'checkpoints', stage)

cfg = Config()

# ── Label maps ───────────────────────────────────────────────────
# These are used only for human-readable output (attention viz, inference).
# Training uses integer labels directly from HuggingFace.
INFORM_MAP = {0: 'not_informative', 1: 'informative'}
DAMAGE_MAP = {0: 'little_or_no_damage', 1: 'mild_damage', 2: 'severe_damage'}
HUMAN_MAP  = {
    0: 'not_humanitarian',        1: 'caution_and_advice',
    2: 'missing_or_found_people', 3: 'injured_or_dead_people',
    4: 'affected_individuals',    5: 'vehicle_damage',
    6: 'infrastructure_damage',   7: 'rescue_volunteering',
}
DISASTER_MAP = {
    'hurricane_harvey': 0, 'hurricane_irma': 1, 'hurricane_maria': 2,
    'iraq_iran_earthquake': 3, 'mexico_earthquake': 4,
    'srilanka_floods': 5, 'california_wildfires': 6,
}
INV_DISASTER = {v: k for k, v in DISASTER_MAP.items()}

print(f"Config ready | n_damage={cfg.n_damage} | device={device}")

"""## 💾 Cell 4 — Google Drive & Directory Setup
Mounts Drive and creates all checkpoint directories.
"""

def setup_drive():
    if not cfg.use_drive:
        print("Drive disabled — checkpoints stored locally (lost on restart).")
        return
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        print("✅ Google Drive mounted.")
    except ImportError:
        print("⚠️  Not in Colab — skipping Drive mount.")
        cfg.use_drive = False
        return
    except Exception as e:
        print(f"Drive mount failed: {e}")
        cfg.use_drive = False
        return

    dirs = [
        cfg.drive_base,
        cfg.ckpt('ssl'),
        cfg.ckpt('finetune'),
        cfg.ckpt('dann'),
        os.path.join(cfg.drive_base, 'logs'),
        os.path.join(cfg.drive_base, 'results'),
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)
    print(f"Directories ready under: {cfg.drive_base}")

# Local fallback dirs (no cfg.data_dir — data comes from HuggingFace)
for d in ['/content/checkpoints/ssl',
          '/content/checkpoints/finetune',
          '/content/checkpoints/dann']:
    os.makedirs(d, exist_ok=True)

setup_drive()

"""## 💾 Cell 5 — Checkpoint Manager
Saves `latest` every epoch and `best` when a metric improves.
"""

class CheckpointManager:
    """
    Saves checkpoints to Drive after every epoch.
    On session restart: call .resume() to continue from where you left off.
    """
    def __init__(self, stage: str, model_name: str):
        # Primary: Drive. Fallback: local /content
        self.primary = cfg.ckpt(stage) if cfg.use_drive else f'/content/checkpoints/{stage}'
        self.local   = f'/content/checkpoints/{stage}'
        self.name    = model_name
        os.makedirs(self.primary, exist_ok=True)
        os.makedirs(self.local,   exist_ok=True)
        self.history: List[dict] = []
        self._best_val = None

    # ── Save ────────────────────────────────────────────────────
    def save(self, model, optimizer, epoch, metrics: dict,
             scheduler=None, higher_is_better=True):
        ckpt = {
            'epoch': epoch,
            'model': model.state_dict(),
            'optim': optimizer.state_dict(),
            'metrics': metrics,
            'ts': time.time(),
        }
        if scheduler:
            ckpt['sched'] = scheduler.state_dict()

        # Determine if best
        key   = next(iter(metrics))          # first metric is the primary one
        val   = metrics[key]
        is_best = (self._best_val is None or
                   (higher_is_better and val > self._best_val) or
                   (not higher_is_better and val < self._best_val))
        if is_best:
            self._best_val = val

        # Write files
        for base in [self.primary, self.local]:
            self._write(ckpt, os.path.join(base, f'{self.name}_latest.pth'))
            if is_best:
                self._write(ckpt, os.path.join(base, f'{self.name}_best.pth'))

        # History
        self.history.append({'epoch': epoch, **metrics})
        hist_path = os.path.join(self.primary, 'history.json')
        with open(hist_path, 'w') as f:
            json.dump(self.history, f, indent=2)

        tag = " ⭐ BEST" if is_best else ""
        print(f"  💾 Saved epoch {epoch:03d} → {self.primary}{tag}")
        return is_best

    def _write(self, obj, path):
        tmp = path + '.tmp'
        torch.save(obj, tmp)
        os.replace(tmp, path)   # atomic rename — safe against partial writes

    # ── Load / Resume ────────────────────────────────────────────
    def resume(self, model, optimizer=None, scheduler=None, best=False):
        """Load checkpoint. Returns (start_epoch, metrics)."""
        tag  = 'best' if best else 'latest'
        name = f'{self.name}_{tag}.pth'
        # Try Drive first, then local
        for base in [self.primary, self.local]:
            path = os.path.join(base, name)
            if os.path.exists(path):
                return self._load(path, model, optimizer, scheduler)
        print(f"  No checkpoint found ({name}). Starting from scratch.")
        return 0, {}

    def _load(self, path, model, optimizer, scheduler):
        print(f"  📂 Loading: {path}")
        # Added weights_only=False to address UnpicklingError in PyTorch >= 2.6
        ckpt = torch.load(path, map_location=device, weights_only=False)

        # Strip DataParallel prefix if present
        sd = {k.replace('module.', ''): v for k, v in ckpt['model'].items()}
        missing, unexpected = model.load_state_dict(sd, strict=False)
        if missing:    print(f"     Missing keys  : {missing[:3]}")
        if unexpected: print(f"     Unexpected keys: {unexpected[:3]}")

        if optimizer and 'optim' in ckpt:
            try:    optimizer.load_state_dict(ckpt['optim'])
            except: print("     ⚠️  Optimizer state mismatch — using fresh.")
        if scheduler and 'sched' in ckpt:
            try:    scheduler.load_state_dict(ckpt['sched'])
            except: pass

        epoch   = ckpt.get('epoch', 0)
        metrics = ckpt.get('metrics', {})
        print(f"     Resumed from epoch {epoch}, metrics={metrics}")
        return epoch, metrics

print("✅ CheckpointManager ready.")

"""## 📂 Cell 6 — Data Loading

### How to download CrisisMMD v2.0
1. Go to **https://crisisnlp.qcri.org/crisismmd**
2. Fill in the academic-use form and submit
3. Download the zip → upload to Google Drive
4. Unzip to a folder and set `DATA_DIR` in Cell 3

### Folder structure expected
```
DATA_DIR/
├── annotations/
│   ├── hurricane_harvey_final_data.tsv
│   ├── hurricane_irma_final_data.tsv
│   ├── ... (one TSV per event)
└── data_image/
    ├── hurricane_harvey/
    │   ├── image_id.jpg
    ├── ...
```
If `DEMO_MODE = True` (Cell 3), a synthetic dataset is created instead.
"""

# ═══════════════════════════════════════════════════════════════
# Download CrisisMMD v2.0 from HuggingFace — runs AFTER cfg is
# defined. ~1.8 GB. First run: 5-10 min. Subsequent runs: fast
# (HF caches the download).
# ═══════════════════════════════════════════════════════════════
!pip install -q datasets

from datasets import load_dataset

# All images land here — this is the one true IMAGE_DIR
IMAGE_DIR = '/content/data/crisismmd/images'
os.makedirs(IMAGE_DIR, exist_ok=True)

# EVENTS list used by Dataset class and leave-one-out eval
EVENTS = list(DISASTER_MAP.keys())

# ── Download ──────────────────────────────────────────────────────
print("Downloading CrisisMMD v2.0 from HuggingFace...")
tasks_hf = {
    'informative':  load_dataset("QCRI/CrisisMMD", "informative"),
    'damage':       load_dataset("QCRI/CrisisMMD", "damage"),
    'humanitarian': load_dataset("QCRI/CrisisMMD", "humanitarian"),
}

# ── Sync class counts into cfg from real HF metadata ─────────────
cfg.n_inform = tasks_hf['informative']['train'].features['label'].num_classes
cfg.n_damage = tasks_hf['damage']['train'].features['label'].num_classes
cfg.n_human  = tasks_hf['humanitarian']['train'].features['label'].num_classes
print(f"Classes confirmed: inform={cfg.n_inform}  damage={cfg.n_damage}  human={cfg.n_human}")

# ── Convert one HF split to a DataFrame, saving images to disk ───
def hf_to_df(task_name, split_name, hf_split):
    rows = []
    for sample in tqdm(hf_split, desc=f'  {task_name}/{split_name}', leave=False):
        img_id   = sample['image_id']
        img_path = os.path.join(IMAGE_DIR, f'{img_id}.jpg')
        if not os.path.exists(img_path) and sample.get('image') is not None:
            try:
                sample['image'].convert('RGB').save(img_path, 'JPEG', quality=90)
            except Exception:
                pass   # skip corrupt images gracefully
        rows.append({
            'tweet_id':           sample['tweet_id'],
            'image_id':           img_id,
            'tweet_text':         sample['tweet_text'],
            'event_name':         sample['event_name'],
            f'label_{task_name}': int(sample['label']),
        })
    return pd.DataFrame(rows)

# ── Build merged DataFrame across all splits ──────────────────────
split_dfs = []
for split_name in ['train', 'dev', 'test']:
    info_df = hf_to_df('informative',  split_name, tasks_hf['informative'][split_name])
    dmg_df  = hf_to_df('damage',       split_name, tasks_hf['damage'][split_name])
    hum_df  = hf_to_df('humanitarian', split_name, tasks_hf['humanitarian'][split_name])

    merged = (
        info_df
        .merge(dmg_df[['tweet_id', 'label_damage']],        on='tweet_id', how='left')
        .merge(hum_df[['tweet_id', 'label_humanitarian']],  on='tweet_id', how='left')
    )
    merged['label_damage']       = merged['label_damage'].fillna(0).astype(int)
    merged['label_humanitarian'] = merged['label_humanitarian'].fillna(0).astype(int)
    merged['domain_id']          = merged['event_name'].map(DISASTER_MAP).fillna(0).astype(int)
    split_dfs.append(merged)

# Rename label_informative → label_text (what CrisisMMDDataset expects)
full_df = (
    pd.concat(split_dfs, ignore_index=True)
    .rename(columns={'label_informative': 'label_text'})
)

print(f"\n✅ Dataset ready: {len(full_df):,} samples")
print(f"   Columns : {list(full_df.columns)}")
print(f"   Events  :\n{full_df['event_name'].value_counts().to_string()}")
print(f"   Images  : {IMAGE_DIR}")

"""## 🗄️ Cell 7 — Dataset Classes"""

# ── Image transforms ─────────────────────────────────────────────
TRAIN_TF = transforms.Compose([
    transforms.Resize((cfg.img_size, cfg.img_size)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(0.2, 0.2, 0.2, 0.05),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
])
EVAL_TF = transforms.Compose([
    transforms.Resize((cfg.img_size, cfg.img_size)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225]),
])

tokenizer = BertTokenizer.from_pretrained(cfg.bert_name)
print(f"Tokenizer loaded: {cfg.bert_name}")


def load_image(image_dir: str, image_id: str, tf) -> torch.Tensor:
    """Loads an image; returns a black tensor on failure."""
    # Try direct path, then event subdirectory
    candidates = [
        os.path.join(image_dir, f'{image_id}.jpg'),
        os.path.join(image_dir, f'{image_id}.png'),
    ]
    # Also search event sub-folders
    for ev in EVENTS:
        candidates.append(os.path.join(image_dir, ev, f'{image_id}.jpg'))

    for p in candidates:
        if os.path.exists(p):
            try:
                return tf(Image.open(p).convert('RGB'))
            except Exception:
                pass
    return torch.zeros(3, cfg.img_size, cfg.img_size)


class CrisisMMDDataset(Dataset):
    """Labeled dataset for Stages 2 and 3."""

    def __init__(self, df: pd.DataFrame, image_dir: str, split: str = 'train'):
        self.df  = df.reset_index(drop=True)
        self.img_dir = image_dir
        self.tf  = TRAIN_TF if split == 'train' else EVAL_TF

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image = load_image(self.img_dir, str(row.get('image_id', '')), self.tf)

        text = str(row.get('tweet_text', ''))
        enc  = tokenizer(text, max_length=cfg.max_len, padding='max_length',
                         truncation=True, return_tensors='pt')

        item = {
            'image':        image,
            'input_ids':    enc['input_ids'].squeeze(0),
            'attention_mask': enc['attention_mask'].squeeze(0),
            'inform_label': int(row.get('label_text', 0)),
            'damage_label': int(row.get('label_damage', 0)),
            'human_label':  int(row.get('label_humanitarian', 0)),
            'domain_label': int(row.get('domain_id', 0)),
        }
        return item


class UnlabeledPairDataset(Dataset):
    """Unlabeled image-text pairs for Stage 1 SSL pre-training."""

    def __init__(self, df: pd.DataFrame, image_dir: str):
        self.df  = df.reset_index(drop=True)
        self.img_dir = image_dir

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        image = load_image(self.img_dir, str(row.get('image_id', '')), TRAIN_TF)
        text  = str(row.get('tweet_text', ''))
        enc   = tokenizer(text, max_length=cfg.max_len, padding='max_length',
                          truncation=True, return_tensors='pt')
        return {
            'image':         image,
            'input_ids':     enc['input_ids'].squeeze(0),
            'attention_mask': enc['attention_mask'].squeeze(0),
        }


# ── Build splits (stratify by event for clean cross-disaster eval) ──
def build_splits(df: pd.DataFrame):
    train_dfs, val_dfs, test_dfs = [], [], []
    for ev in df['event_name'].unique():
        sub = df[df['event_name'] == ev].sample(frac=1, random_state=SEED)
        n   = len(sub)
        t1, t2 = int(n * 0.70), int(n * 0.85)
        train_dfs.append(sub.iloc[:t1])
        val_dfs.append(sub.iloc[t1:t2])
        test_dfs.append(sub.iloc[t2:])
    return (pd.concat(train_dfs), pd.concat(val_dfs), pd.concat(test_dfs))

train_df, val_df, test_df = build_splits(full_df)
print(f"Split: train={len(train_df):,}  val={len(val_df):,}  test={len(test_df):,}")

train_ds = CrisisMMDDataset(train_df, IMAGE_DIR, split='train')
val_ds   = CrisisMMDDataset(val_df,   IMAGE_DIR, split='val')
test_ds  = CrisisMMDDataset(test_df,  IMAGE_DIR, split='test')
ssl_ds   = UnlabeledPairDataset(full_df, IMAGE_DIR)  # all data, no labels

def make_loader(ds, bs, shuffle=True):
    return DataLoader(ds, batch_size=bs, shuffle=shuffle,
                      num_workers=2, pin_memory=True, drop_last=shuffle)

print("✅ Datasets and DataLoaders ready.")

"""## 🧠 Cell 8 — Model Architecture
**ImageEncoder + TextEncoder + CrossModalTransformer + CrisisNet + DANN**
"""

# ══════════════════════════════════════════════════════════════
# 1. IMAGE ENCODER  (ResNet-50 backbone + linear projection)
# ══════════════════════════════════════════════════════════════
class ImageEncoder(nn.Module):
    def __init__(self, proj_dim=512):
        super().__init__()
        base = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
        # Keep spatial feature map (B, 2048, 7, 7) — drop avgpool + fc
        self.backbone   = nn.Sequential(*list(base.children())[:-2])
        self.global_pool= nn.AdaptiveAvgPool2d(1)
        self.proj       = nn.Sequential(nn.Linear(2048, proj_dim), nn.LayerNorm(proj_dim))

    def forward(self, x, mode='spatial'):
        feats = self.backbone(x)                     # (B, 2048, 7, 7)
        if mode == 'global':
            g = self.global_pool(feats).flatten(1)   # (B, 2048)
            return self.proj(g)                      # (B, proj_dim)
        # spatial tokens for cross-attention
        B, C, H, W = feats.shape
        tokens = feats.permute(0,2,3,1).reshape(B, H*W, C)  # (B, 49, 2048)
        return self.proj(tokens)                     # (B, 49, proj_dim)


# ══════════════════════════════════════════════════════════════
# 2. TEXT ENCODER  (BERT-base + linear projection)
# ══════════════════════════════════════════════════════════════
class TextEncoder(nn.Module):
    def __init__(self, proj_dim=512, bert_name='bert-base-uncased'):
        super().__init__()
        self.bert = BertModel.from_pretrained(bert_name)
        self.proj = nn.Sequential(nn.Linear(768, proj_dim), nn.LayerNorm(proj_dim))

    def forward(self, input_ids, attention_mask, mode='sequence'):
        out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        hidden = out.last_hidden_state                # (B, L, 768)
        projected = self.proj(hidden)                 # (B, L, proj_dim)
        if mode == 'cls':
            return projected[:, 0, :]                # (B, proj_dim)
        return projected                              # (B, L, proj_dim)


# ══════════════════════════════════════════════════════════════
# 3. CROSS-MODAL TRANSFORMER  (bidirectional cross-attention)
# ══════════════════════════════════════════════════════════════
class CrossModalLayer(nn.Module):
    """One cross-attention + FFN block (query attends to kv)."""
    def __init__(self, dim, heads, dropout=0.1):
        super().__init__()
        self.attn  = nn.MultiheadAttention(dim, heads, dropout=dropout, batch_first=True)
        self.norm1 = nn.LayerNorm(dim)
        self.ffn   = nn.Sequential(
            nn.Linear(dim, dim*4), nn.GELU(), nn.Dropout(dropout),
            nn.Linear(dim*4, dim), nn.Dropout(dropout),
        )
        self.norm2 = nn.LayerNorm(dim)
        self.drop  = nn.Dropout(dropout)

    def forward(self, q, kv, kv_mask=None):
        a, w = self.attn(q, kv, kv, key_padding_mask=kv_mask,
                         need_weights=True, average_attn_weights=True)
        q = self.norm1(q + self.drop(a))
        q = self.norm2(q + self.ffn(q))
        return q, w


class CrossModalTransformer(nn.Module):
    def __init__(self, dim, heads, n_layers=2, dropout=0.1):
        super().__init__()
        # Image → Text cross-attention
        self.i2t = nn.ModuleList([CrossModalLayer(dim, heads, dropout) for _ in range(n_layers)])
        # Text → Image cross-attention
        self.t2i = nn.ModuleList([CrossModalLayer(dim, heads, dropout) for _ in range(n_layers)])
        # Self-attention (image)
        self.isa = nn.ModuleList([
            nn.TransformerEncoderLayer(dim, heads, dim*4, dropout, batch_first=True, norm_first=True)
            for _ in range(n_layers)
        ])
        # Self-attention (text)
        self.tsa = nn.ModuleList([
            nn.TransformerEncoderLayer(dim, heads, dim*4, dropout, batch_first=True, norm_first=True)
            for _ in range(n_layers)
        ])
        self.norm = nn.LayerNorm(dim)

    def forward(self, img_tok, txt_tok, txt_pad=None):
        """
        img_tok : (B, 49, D)   text_tok : (B, L, D)
        txt_pad : (B, L) True=padding
        Returns : fused (B, D), last cross-attn weights (B, 49, L)
        """
        attn_w = None
        for i2t_l, t2i_l, isa_l, tsa_l in zip(self.i2t, self.t2i, self.isa, self.tsa):
            img_tok, attn_w = i2t_l(img_tok, txt_tok, txt_pad)
            txt_tok, _      = t2i_l(txt_tok, img_tok)
            img_tok = isa_l(img_tok)
            txt_tok = tsa_l(txt_tok, src_key_padding_mask=txt_pad)

        combined = torch.cat([img_tok, txt_tok], dim=1)  # (B, 49+L, D)
        fused    = self.norm(combined.mean(dim=1))        # (B, D)
        return fused, attn_w


# ══════════════════════════════════════════════════════════════
# 4. TASK HEADS (three independent classifiers)
# ══════════════════════════════════════════════════════════════
class TaskHeads(nn.Module):
    def __init__(self, dim, n_info, n_dmg, n_hum, dropout=0.1):
        super().__init__()
        def _head(n):
            return nn.Sequential(
                nn.Dropout(dropout), nn.Linear(dim, dim//2),
                nn.GELU(), nn.Dropout(dropout), nn.Linear(dim//2, n)
            )
        self.info = _head(n_info)
        self.dmg  = _head(n_dmg)
        self.hum  = _head(n_hum)

    def forward(self, x):
        return {'informative': self.info(x),
                'damage':      self.dmg(x),
                'humanitarian':self.hum(x)}


# ══════════════════════════════════════════════════════════════
# 5. FULL CRISISNET MODEL
# ══════════════════════════════════════════════════════════════
class CrisisNet(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.img_enc = ImageEncoder(cfg.proj_dim)
        self.txt_enc = TextEncoder(cfg.proj_dim, cfg.bert_name)
        self.fusion  = CrossModalTransformer(cfg.proj_dim, cfg.num_heads,
                                              cfg.num_layers, cfg.dropout)
        self.heads   = TaskHeads(cfg.proj_dim, cfg.n_inform, cfg.n_damage,
                                  cfg.n_human, cfg.dropout)

    def forward(self, images, input_ids, attention_mask, return_attn=False):
        img_tok  = self.img_enc(images, mode='spatial')
        txt_tok  = self.txt_enc(input_ids, attention_mask, mode='sequence')
        txt_pad  = (attention_mask == 0)
        fused, w = self.fusion(img_tok, txt_tok, txt_pad)
        out      = self.heads(fused)
        return (out, w) if return_attn else out


# ══════════════════════════════════════════════════════════════
# 6. CLIP-LIKE MODEL  (for Stage 1 SSL — global features only)
# ══════════════════════════════════════════════════════════════
class CLIPModel(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.img_enc    = ImageEncoder(cfg.proj_dim)
        self.txt_enc    = TextEncoder(cfg.proj_dim, cfg.bert_name)
        self.log_scale  = nn.Parameter(torch.ones([]) * math.log(1 / cfg.ssl_temp))

    def forward(self, images, input_ids, attention_mask):
        img = F.normalize(self.img_enc(images, mode='global'), dim=-1)
        txt = F.normalize(self.txt_enc(input_ids, attention_mask, mode='cls'), dim=-1)
        return img, txt, self.log_scale.exp().clamp(max=100)


# ══════════════════════════════════════════════════════════════
# 7. DANN MODEL  (Stage 3 — domain-adversarial neural network)
# ══════════════════════════════════════════════════════════════
class GradRevFn(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, alpha):
        ctx.alpha = alpha; return x
    @staticmethod
    def backward(ctx, g):
        return -ctx.alpha * g, None

class GradRev(nn.Module):
    def forward(self, x, alpha=1.0):
        return GradRevFn.apply(x, alpha)

class CrisisNetDANN(CrisisNet):
    def __init__(self, cfg):
        super().__init__(cfg)
        self.grl     = GradRev()
        self.dom_cls = nn.Sequential(
            nn.Linear(cfg.proj_dim, 256), nn.ReLU(),
            nn.Dropout(cfg.dropout),     nn.Linear(256, cfg.n_disasters)
        )

    def forward(self, images, input_ids, attention_mask, alpha=1.0, return_attn=False):
        img_tok  = self.img_enc(images, mode='spatial')
        txt_tok  = self.txt_enc(input_ids, attention_mask, mode='sequence')
        txt_pad  = (attention_mask == 0)
        fused, w = self.fusion(img_tok, txt_tok, txt_pad)
        tasks    = self.heads(fused)
        domain   = self.dom_cls(self.grl(fused, alpha))
        if return_attn:
            return tasks, domain, w
        return tasks, domain


# ── Quick sanity check ───────────────────────────────────────────
def _check(model, name):
    n = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"  {name:<20} {n/1e6:6.1f}M trainable params")

print("Model parameter counts:")
_check(CLIPModel(cfg),        'CLIPModel (Stage 1)')
_check(CrisisNet(cfg),        'CrisisNet (Stage 2)')
_check(CrisisNetDANN(cfg),    'CrisisNetDANN (Stage 3)')
print("✅ All models defined.")

"""## 📐 Cell 9 — Loss Functions & Evaluation"""

# ── InfoNCE (CLIP-style) loss ────────────────────────────────────
class InfoNCELoss(nn.Module):
    def forward(self, img, txt, scale):
        """img, txt: L2-normalised (B, D). scale: scalar temperature."""
        logits = scale * img @ txt.T   # (B, B)
        labels = torch.arange(len(img), device=img.device)
        loss_i = F.cross_entropy(logits,   labels)
        loss_t = F.cross_entropy(logits.T, labels)
        return (loss_i + loss_t) / 2


# ── Multi-task loss ───────────────────────────────────────────────
class MultiTaskLoss(nn.Module):
    def __init__(self, w_info=1.0, w_dmg=0.5, w_hum=0.5):
        super().__init__()
        self.w = {'informative': w_info, 'damage': w_dmg, 'humanitarian': w_hum}

    def forward(self, logits: dict, batch: dict):
        total = 0.0
        key_map = {
            'informative': 'inform_label',
            'damage':      'damage_label',
            'humanitarian':'human_label',
        }
        for task, lbl_key in key_map.items():
            if lbl_key in batch:
                labels = batch[lbl_key].to(device)
                total += self.w[task] * F.cross_entropy(logits[task], labels)
        return total


# ── Evaluation ────────────────────────────────────────────────────
@torch.no_grad()
def evaluate(model, loader, stage='finetune'):
    model.eval()
    preds = {'informative': [], 'damage': [], 'humanitarian': []}
    trues = {'informative': [], 'damage': [], 'humanitarian': []}
    key_map = {
        'informative': 'inform_label',
        'damage':      'damage_label',
        'humanitarian':'human_label',
    }

    for batch in tqdm(loader, desc='Evaluating', leave=False):
        images = batch['image'].to(device)
        ids    = batch['input_ids'].to(device)
        mask   = batch['attention_mask'].to(device)

        if stage == 'dann':
            logits, _ = model(images, ids, mask, alpha=0.0)
        else:
            logits    = model(images, ids, mask)

        for task, lbl_key in key_map.items():
            if lbl_key in batch:
                pred = logits[task].argmax(dim=1).cpu().numpy()
                true = batch[lbl_key].numpy()
                preds[task].extend(pred)
                trues[task].extend(true)

    metrics = {}
    for task in preds:
        if len(preds[task]) == 0: continue
        p, t = np.array(preds[task]), np.array(trues[task])
        metrics[f'{task}_f1']  = f1_score(t, p, average='macro', zero_division=0)
        metrics[f'{task}_acc'] = accuracy_score(t, p)

    if metrics:
        avg_f1 = np.mean([v for k, v in metrics.items() if '_f1' in k])
        metrics['avg_f1'] = avg_f1

    model.train()
    return metrics


def print_metrics(metrics: dict, epoch: int):
    hdr = f"  Epoch {epoch:03d}"
    for k, v in metrics.items():
        hdr += f"  |  {k}: {v:.4f}"
    print(hdr)


print("✅ Loss functions and evaluation ready.")

"""## 🔵 Cell 10 — Stage 1: SSL Pre-training
Trains encoders with a CLIP-style contrastive objective on unlabeled pairs.
Checkpoint saved every epoch to Drive.
"""

def train_ssl(resume: bool = True):
    """Stage 1: CLIP-style contrastive pre-training."""
    print("\n" + "="*60)
    print("STAGE 1 — SSL Pre-training")
    print("="*60)

    model = CLIPModel(cfg).to(device)
    loss_fn = InfoNCELoss()
    ckpt_mgr = CheckpointManager('ssl', 'clip')

    ssl_loader = make_loader(ssl_ds, cfg.ssl_bs, shuffle=True)
    total_steps = len(ssl_loader) * cfg.ssl_epochs

    optimizer = AdamW(model.parameters(), lr=cfg.ssl_lr, weight_decay=cfg.ssl_wd)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps  = max(1, int(0.05 * total_steps)),
        num_training_steps= total_steps,
    )
    scaler = GradScaler(enabled=cfg.use_amp)

    # ── Resume ────────────────────────────────────────────────────
    start_epoch = 0
    if resume:
        start_epoch, _ = ckpt_mgr.resume(model, optimizer, scheduler)

    best_loss = float('inf')

    for epoch in range(start_epoch, cfg.ssl_epochs):
        model.train()
        run_loss = 0.0
        pbar = tqdm(ssl_loader, desc=f'SSL {epoch+1:02d}/{cfg.ssl_epochs}', leave=False)

        for batch in pbar:
            images = batch['image'].to(device, non_blocking=True)
            ids    = batch['input_ids'].to(device, non_blocking=True)
            mask   = batch['attention_mask'].to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with autocast(enabled=cfg.use_amp):
                img_f, txt_f, scale = model(images, ids, mask)
                loss = loss_fn(img_f, txt_f, scale)

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            run_loss += loss.item()
            pbar.set_postfix({'loss': f'{run_loss/(pbar.n+1):.4f}',
                               'scale': f'{scale.item():.2f}'})

        avg_loss = run_loss / len(ssl_loader)
        is_best  = avg_loss < best_loss
        if is_best: best_loss = avg_loss

        # ── Save every epoch ──────────────────────────────────────
        ckpt_mgr.save(model, optimizer, epoch+1,
                       metrics={'ssl_loss': avg_loss},
                       scheduler=scheduler,
                       higher_is_better=False)

        print(f"  Epoch {epoch+1:02d}/{cfg.ssl_epochs}  loss={avg_loss:.4f}"
              f"  scale={scale.item():.2f}{'  ⭐ best' if is_best else ''}")

    print("\n✅ Stage 1 complete.")
    return model


# ── Run Stage 1 ──────────────────────────────────────────────────
# Set resume=True to continue from an existing checkpoint (default)
# Set resume=False to start fresh even if a checkpoint exists
ssl_model = train_ssl(resume=True)

"""## 🟡 Cell 11 — Stage 2: Multi-task Fine-tuning
Loads SSL-pre-trained encoders and trains the full multimodal model on CrisisMMD labeled data.
Checkpoint saved every epoch.
"""

def transfer_ssl_weights(ssl_model: CLIPModel, crisis_model: CrisisNet):
    """Copy encoder weights from CLIP model to CrisisNet."""
    crisis_model.img_enc.load_state_dict(ssl_model.img_enc.state_dict(), strict=False)
    crisis_model.txt_enc.load_state_dict(ssl_model.txt_enc.state_dict(), strict=False)
    print("  ✅ SSL encoder weights transferred to CrisisNet.")


def train_finetune(ssl_model_or_path=None, resume: bool = True):
    """Stage 2: supervised multi-task fine-tuning."""
    print("\n" + "="*60)
    print("STAGE 2 — Multi-task Fine-tuning")
    print("="*60)

    model    = CrisisNet(cfg).to(device)
    loss_fn  = MultiTaskLoss(cfg.lam_info, cfg.lam_dmg, cfg.lam_hum)
    ckpt_mgr = CheckpointManager('finetune', 'crisisnet')

    # ── Transfer SSL weights ────────────────────────────────────
    if ssl_model_or_path is not None:
        if isinstance(ssl_model_or_path, CLIPModel):
            transfer_ssl_weights(ssl_model_or_path, model)
        elif isinstance(ssl_model_or_path, str) and os.path.exists(ssl_model_or_path):
            ssl_m = CLIPModel(cfg).to(device)
            ssl_m.load_state_dict(torch.load(ssl_model_or_path, map_location=device)['model'])
            transfer_ssl_weights(ssl_m, model)
    else:
        print("  ⚠️  No SSL weights provided — using ImageNet + random init.")

    # ── Optimiser with layer-wise LR (BERT lower, rest higher) ───
    bert_params  = list(model.txt_enc.bert.parameters())
    other_params = [p for p in model.parameters()
                    if not any(p is bp for bp in bert_params)]
    optimizer = AdamW([
        {'params': bert_params,  'lr': cfg.ft_lr * 0.1},
        {'params': other_params, 'lr': cfg.ft_lr},
    ], weight_decay=cfg.ft_wd)

    train_loader = make_loader(train_ds, cfg.ft_bs, shuffle=True)
    val_loader   = make_loader(val_ds,   cfg.ft_bs, shuffle=False)
    total_steps  = len(train_loader) * cfg.ft_epochs
    scheduler    = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps  = max(1, int(cfg.ft_warmup * total_steps)),
        num_training_steps= total_steps,
    )
    scaler = GradScaler(enabled=cfg.use_amp)

    # ── Resume ────────────────────────────────────────────────────
    start_epoch = 0
    if resume:
        start_epoch, prev = ckpt_mgr.resume(model, optimizer, scheduler)

    for epoch in range(start_epoch, cfg.ft_epochs):
        model.train()
        run_loss = 0.0
        pbar = tqdm(train_loader, desc=f'FT {epoch+1:02d}/{cfg.ft_epochs}', leave=False)

        for batch in pbar:
            images = batch['image'].to(device, non_blocking=True)
            ids    = batch['input_ids'].to(device, non_blocking=True)
            mask   = batch['attention_mask'].to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with autocast(enabled=cfg.use_amp):
                logits = model(images, ids, mask)
                loss   = loss_fn(logits, batch)

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            scaler.step(optimizer)
            scaler.update()
            scheduler.step()

            run_loss += loss.item()
            pbar.set_postfix({'loss': f'{run_loss/(pbar.n+1):.4f}'})

        avg_loss = run_loss / len(train_loader)

        # ── Validate ──────────────────────────────────────────────
        val_metrics = evaluate(model, val_loader, stage='finetune')
        val_metrics['train_loss'] = avg_loss
        print_metrics(val_metrics, epoch+1)

        # ── Save every epoch ──────────────────────────────────────
        ckpt_mgr.save(model, optimizer, epoch+1,
                       metrics=val_metrics,
                       scheduler=scheduler,
                       higher_is_better=True)

    print("\n✅ Stage 2 complete.")
    return model


# ── Run Stage 2 ──────────────────────────────────────────────────
ft_model = train_finetune(ssl_model_or_path=ssl_model, resume=True)

"""## 🟠 Cell 12 — Stage 3: Cross-Disaster Domain Adaptation
DANN with gradient reversal layer. Leave-one-disaster-out evaluation.
"""

def get_alpha(epoch, total):
    """Progressive DANN alpha: starts ~0, approaches 1."""
    p = epoch / max(total, 1)
    return 2.0 / (1.0 + math.exp(-10 * p)) - 1.0


def train_dann(ft_model_or_path=None, resume: bool = True):
    """Stage 3: domain-adversarial fine-tuning."""
    print("\n" + "="*60)
    print("STAGE 3 — DANN Domain Adaptation")
    print("="*60)

    model    = CrisisNetDANN(cfg).to(device)
    loss_fn  = MultiTaskLoss(cfg.lam_info, cfg.lam_dmg, cfg.lam_hum)
    ckpt_mgr = CheckpointManager('dann', 'crisisnet_dann')

    # ── Load fine-tuned weights ──────────────────────────────────
    if ft_model_or_path is not None:
        src = ft_model_or_path
        if isinstance(src, CrisisNet):
            model.load_state_dict(src.state_dict(), strict=False)
            print("  Fine-tuned weights loaded from CrisisNet object.")
        elif isinstance(src, str) and os.path.exists(src):
            sd = torch.load(src, map_location=device)['model']
            model.load_state_dict(sd, strict=False)
            print(f"  Fine-tuned weights loaded from {src}")
    else:
        # Try to load from Stage 2 checkpoint automatically
        ft_ckpt = os.path.join(cfg.ckpt('finetune'), 'crisisnet_best.pth')
        if os.path.exists(ft_ckpt):
            sd = torch.load(ft_ckpt, map_location=device)['model']
            model.load_state_dict(sd, strict=False)
            print(f"  Auto-loaded Stage 2 best checkpoint: {ft_ckpt}")

    optimizer = AdamW(model.parameters(), lr=cfg.dann_lr, weight_decay=cfg.ft_wd)
    train_loader = make_loader(train_ds, cfg.dann_bs, shuffle=True)
    val_loader   = make_loader(val_ds,   cfg.dann_bs, shuffle=False)
    scaler = GradScaler(enabled=cfg.use_amp)

    # ── Resume ────────────────────────────────────────────────────
    start_epoch = 0
    if resume:
        start_epoch, _ = ckpt_mgr.resume(model, optimizer)

    for epoch in range(start_epoch, cfg.dann_epochs):
        model.train()
        alpha    = get_alpha(epoch, cfg.dann_epochs)
        run_loss = 0.0
        pbar = tqdm(train_loader, desc=f'DANN {epoch+1:02d}/{cfg.dann_epochs}  α={alpha:.3f}',
                    leave=False)

        for batch in pbar:
            images = batch['image'].to(device, non_blocking=True)
            ids    = batch['input_ids'].to(device, non_blocking=True)
            mask   = batch['attention_mask'].to(device, non_blocking=True)
            dom_lbl= batch['domain_label'].to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with autocast(enabled=cfg.use_amp):
                task_out, dom_out = model(images, ids, mask, alpha=alpha)
                task_loss = loss_fn(task_out, batch)
                dom_loss  = F.cross_entropy(dom_out, dom_lbl)
                loss      = task_loss + cfg.lam_domain * dom_loss

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            scaler.step(optimizer)
            scaler.update()

            run_loss += loss.item()
            pbar.set_postfix({'loss': f'{run_loss/(pbar.n+1):.4f}', 'α': f'{alpha:.3f}'})

        avg_loss = run_loss / len(train_loader)

        # ── Validate ──────────────────────────────────────────────
        val_metrics = evaluate(model, val_loader, stage='dann')
        val_metrics['train_loss'] = avg_loss
        print_metrics(val_metrics, epoch+1)

        # ── Save every epoch ──────────────────────────────────────
        ckpt_mgr.save(model, optimizer, epoch+1,
                       metrics=val_metrics,
                       higher_is_better=True)

    print("\n✅ Stage 3 complete.")
    return model


# ── Leave-one-disaster-out evaluation ────────────────────────────
@torch.no_grad()
def leave_one_out_eval(model, full_df, img_dir):
    """Evaluates cross-disaster generalisation for each event held out."""
    model.eval()
    results = {}
    for ev in EVENTS:
        test_sub = full_df[full_df['event_name'] == ev]
        if len(test_sub) == 0: continue
        ds = CrisisMMDDataset(test_sub, img_dir, split='val')
        ld = make_loader(ds, cfg.dann_bs, shuffle=False)
        m  = evaluate(model, ld, stage='dann')
        results[ev] = m.get('avg_f1', 0.0)
        print(f"  {ev:<35} avg_F1 = {results[ev]:.4f}")
    return results


# ── Run Stage 3 ──────────────────────────────────────────────────
dann_model = train_dann(ft_model_or_path=ft_model, resume=True)

# Leave-one-disaster-out
print("\nLeave-one-disaster-out transfer evaluation:")
lodo_results = leave_one_out_eval(dann_model, full_df, IMAGE_DIR)

"""## 📊 Cell 13 — Ablation Table & Full Evaluation"""

def run_ablation(full_df, img_dir):
    """
    Runs 6 model configurations and builds the ablation table.
    Requires trained checkpoints from Stages 1-3.
    """

    rows = []
    test_loader = make_loader(test_ds, cfg.ft_bs, shuffle=False)

    configs = [
        ('Image-only (ResNet-50)', None, 'image_only'),
        ('Text-only (BERT)',        None, 'text_only'),
        ('Late fusion (concat)',    None, 'late_fusion'),
        ('Cross-attn, no SSL',     None, 'no_ssl'),
        ('Full model (SSL + cross-attn)', os.path.join(cfg.ckpt('finetune'), 'crisisnet_best.pth'), 'full'),
        ('Full model + DANN',      os.path.join(cfg.ckpt('dann'),    'crisisnet_dann_best.pth'), 'dann'),
    ]

    for name, ckpt_path, variant in configs:
        print(f"\nEvaluating: {name}")
        if ckpt_path and os.path.exists(ckpt_path):
            if variant == 'dann':
                m = CrisisNetDANN(cfg).to(device)
            else:
                m = CrisisNet(cfg).to(device)
            sd = torch.load(ckpt_path, map_location=device)['model']
            m.load_state_dict(sd, strict=False)
            metrics = evaluate(m, test_loader, stage='dann' if variant=='dann' else 'finetune')
        else:
            print(f"  ⚠️  Checkpoint not found — skipping. Run training cells first.")
            metrics = {k: float('nan') for k in ['informative_f1','damage_f1',
                                                   'humanitarian_f1','avg_f1']}

        rows.append({
            'Configuration': name,
            'Inform F1':  metrics.get('informative_f1', float('nan')),
            'Damage F1':  metrics.get('damage_f1',      float('nan')),
            'Human F1':   metrics.get('humanitarian_f1',float('nan')),
            'Avg F1':     metrics.get('avg_f1',         float('nan')),
        })

    abl = pd.DataFrame(rows)
    print("\n" + "="*60)
    print("ABLATION TABLE")
    print("="*60)
    pd.set_option('display.float_format', '{:.4f}'.format)
    print(abl.to_string(index=False))

    # ── Plot ──────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 4))
    x = np.arange(len(abl))
    for i, col in enumerate(['Inform F1', 'Damage F1', 'Human F1']):
        vals = abl[col].fillna(0).values
        ax.bar(x + i*0.25, vals, 0.25, label=col)
    ax.set_xticks(x + 0.25)
    ax.set_xticklabels(abl['Configuration'], rotation=20, ha='right', fontsize=8)
    ax.set_ylabel('Macro F1')
    ax.set_title('Ablation: per-task F1 across model configurations')
    ax.legend()
    ax.set_ylim(0, 1)
    plt.tight_layout()
    out = os.path.join(cfg.drive_base if cfg.use_drive else '/content', 'results', 'ablation.png')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    plt.savefig(out, dpi=150)
    plt.show()
    print(f"\nPlot saved: {out}")
    return abl


ablation_df = run_ablation(full_df, IMAGE_DIR)

"""## 🔍 Cell 14 — Cross-Attention Visualisation
Shows which image regions the model attends to for a given tweet.
"""

@torch.no_grad()
def visualise_attention(model, image_path: str, tweet_text: str,
                        save_path: str = None):
    """
    Overlays cross-attention weights (image→text) on the input image.
    Weights show which of the 7x7 spatial patches attend most to the tweet.
    """
    model.eval()

    # ── Load and transform image ──────────────────────────────────
    raw = Image.open(image_path).convert('RGB').resize((224, 224))
    img_tensor = EVAL_TF(raw).unsqueeze(0).to(device)

    enc  = tokenizer(tweet_text, max_length=cfg.max_len, padding='max_length',
                     truncation=True, return_tensors='pt')
    ids  = enc['input_ids'].to(device)
    mask = enc['attention_mask'].to(device)

    # ── Forward pass with attention ───────────────────────────────
    if isinstance(model, CrisisNetDANN):
        task_out, dom_out, attn_w = model(img_tensor, ids, mask, alpha=0.0, return_attn=True)
        logits = task_out
    else:
        logits, attn_w = model(img_tensor, ids, mask, return_attn=True)

    # attn_w: (1, 49, L) — average over text dim → (49,) → reshape (7, 7)
    attn = attn_w[0].mean(dim=-1).cpu().numpy().reshape(7, 7)
    attn = (attn - attn.min()) / (attn.max() - attn.min() + 1e-8)

    # ── Decode predictions ────────────────────────────────────────
    info_pred = logits['informative'].argmax(1).item()
    dmg_pred  = logits['damage'].argmax(1).item()
    hum_pred  = logits['humanitarian'].argmax(1).item()
    inv_info  = {v:k for k,v in INFORM_MAP.items()}
    inv_dmg   = {v:k for k,v in DAMAGE_MAP.items()}
    inv_hum   = {v:k for k,v in HUMAN_MAP.items()}

    # ── Plot ──────────────────────────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(14, 4))

    axes[0].imshow(raw)
    axes[0].set_title('Input image', fontsize=10)
    axes[0].axis('off')

    axes[1].imshow(raw)
    axes[1].imshow(np.kron(attn, np.ones((32, 32))),
                   alpha=0.55, cmap='hot', vmin=0, vmax=1)
    axes[1].set_title('Cross-attention (image→text)', fontsize=10)
    axes[1].axis('off')

    axes[2].axis('off')
    pred_text = (
        f"Tweet:\n{tweet_text[:120]}...\n\n"
        f"Informative : {inv_info.get(info_pred,'?')}\n"
        f"Damage      : {inv_dmg.get(dmg_pred,'?')}\n"
        f"Humanitarian: {inv_hum.get(hum_pred,'?')}"
    )
    axes[2].text(0.05, 0.5, pred_text, transform=axes[2].transAxes,
                 fontsize=8, va='center', wrap=True,
                 bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8))

    plt.suptitle('CrisisNet — Cross-Attention Visualisation', fontsize=12, fontweight='bold')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()


# ── Demo: run on first test sample ─────────────────────────────
sample = test_df.iloc[0]
# Find image path
img_path = None
for base in [IMAGE_DIR] + [os.path.join(IMAGE_DIR, ev) for ev in EVENTS]:
    for ext in ['.jpg', '.png']:
        p = os.path.join(base, str(sample.get('image_id','')) + ext)
        if os.path.exists(p):
            img_path = p; break
    if img_path: break

if img_path:
    save = os.path.join(cfg.drive_base if cfg.use_drive else '/content',
                        'results', 'attention_demo.png')
    visualise_attention(dann_model, img_path,
                         str(sample.get('tweet_text', 'No text')),
                         save_path=save)
else:
    print("⚠️  No image found for demo sample. Run with your own image_path.")

"""## 🚀 Cell 15 — Single-Sample Inference
Load a trained checkpoint and classify any tweet-image pair.
"""

def load_best_model(stage='dann'):
    """Loads the best checkpoint for a given stage."""
    names = {'ssl':'clip', 'finetune':'crisisnet', 'dann':'crisisnet_dann'}
    ModelClass = {'ssl': CLIPModel, 'finetune': CrisisNet, 'dann': CrisisNetDANN}

    m = ModelClass[stage](cfg).to(device)
    ckpt_mgr = CheckpointManager(stage, names[stage])
    ckpt_mgr.resume(m, best=True)
    m.eval()
    return m


def predict(image_path_or_url: str, tweet_text: str,
            model=None, verbose=True):
    """
    Classify a crisis tweet-image pair.

    Returns dict with keys: informative, damage, humanitarian,
    plus confidence scores for each class.
    """
    if model is None:
        model = load_best_model('dann')

    # ── Load image ────────────────────────────────────────────────
    if image_path_or_url.startswith('http'):
        import urllib.request, io
        data = urllib.request.urlopen(image_path_or_url).read()
        raw  = Image.open(io.BytesIO(data)).convert('RGB')
    else:
        raw = Image.open(image_path_or_url).convert('RGB')

    img_t = EVAL_TF(raw).unsqueeze(0).to(device)

    # ── Tokenise ──────────────────────────────────────────────────
    enc = tokenizer(tweet_text, max_length=cfg.max_len, padding='max_length',
                    truncation=True, return_tensors='pt')
    ids  = enc['input_ids'].to(device)
    mask = enc['attention_mask'].to(device)

    # ── Inference ─────────────────────────────────────────────────
    with torch.no_grad():
        if isinstance(model, CrisisNetDANN):
            logits, _, _ = model(img_t, ids, mask, alpha=0.0, return_attn=True)
        else:
            logits, _ = model(img_t, ids, mask, return_attn=True)

    def decode(logit_vec, inv_map):
        probs = F.softmax(logit_vec, dim=-1).squeeze()
        pred  = probs.argmax().item()
        return inv_map.get(pred, 'unknown'), {inv_map.get(i,'?'): f'{p:.3f}'
                                               for i, p in enumerate(probs.tolist())}

    inv_info = {v:k for k,v in INFORM_MAP.items()}
    inv_dmg  = {v:k for k,v in DAMAGE_MAP.items()}
    inv_hum  = {v:k for k,v in HUMAN_MAP.items()}

    r_info, c_info = decode(logits['informative'], inv_info)
    r_dmg,  c_dmg  = decode(logits['damage'],      inv_dmg)
    r_hum,  c_hum  = decode(logits['humanitarian'], inv_hum)

    result = {
        'informative':    r_info,  'informative_conf':    c_info,
        'damage':         r_dmg,   'damage_conf':         c_dmg,
        'humanitarian':   r_hum,   'humanitarian_conf':   c_hum,
    }

    if verbose:
        print(f"\nTweet       : {tweet_text[:100]}")
        print(f"Informative : {r_info}  (conf: {c_info.get(r_info,'?')})")
        print(f"Damage      : {r_dmg}   (conf: {c_dmg.get(r_dmg,'?')})")
        print(f"Humanitarian: {r_hum}   (conf: {c_hum.get(r_hum,'?')})")

    return result


# ── Example ────────────────────────────────────────────────────
example_text = ("People stranded on rooftops in Houston, water rising fast. "
                "Rescue helicopters needed immediately. #HurricaneHarvey")

# Use a demo image (replace with a real crisis photo path)
demo_img = list(Path(IMAGE_DIR).rglob('*.jpg'))
if demo_img:
    out = predict(str(demo_img[0]), example_text, model=dann_model)
else:
    print("No images found in IMAGE_DIR — provide a real image path to test inference.")

"""## ✅ Summary

| Stage | Model saved | Location |
|-------|-------------|----------|
| 1 — SSL | `clip_best.pth`, `clip_latest.pth` | Drive/checkpoints/ssl/ |
| 2 — Fine-tune | `crisisnet_best.pth`, `crisisnet_latest.pth` | Drive/checkpoints/finetune/ |
| 3 — DANN | `crisisnet_dann_best.pth`, `crisisnet_dann_latest.pth` | Drive/checkpoints/dann/ |

### To resume after a session crash
Simply re-run all cells from top — each training cell calls `ckpt_mgr.resume()`
which automatically loads the latest checkpoint from Drive before training begins.

### To run inference only
```python
model = load_best_model('dann')          # loads from Drive
result = predict('path/to/image.jpg', 'tweet text here', model=model)
```
"""